"""Experiment proposer — the inventive layer.

After learnings + competitor insights are refreshed, the experimenter
looks at:

  1. What styles / hooks / durations we've TRIED (from clips table).
  2. What competitors are DOING THAT WE HAVEN'T (from competitor_insights).
  3. Where the gap is widest = the most informative experiment to run.

It then proposes 1-3 specific, testable experiments per campaign and
Telegram-pings Chris with the list. Each experiment is parameterized so
the orchestrator could (later) auto-execute it in an explore slot.

Designed to be model-driven where it matters: the experiment proposals
themselves are generated by Claude with the data as context, so the
system can be genuinely creative ("you've never tried opening with a
shocking number — competitor winners do, try '$2 vs $200 ramen'").
"""

from __future__ import annotations

import json
from collections import Counter
from datetime import datetime, timezone
from datetime import datetime, timezone
from typing import Optional

from loguru import logger

from config import settings
from db.repository import Repository
from .learnings import get_learnings
from .competitor_learner import get_competitor_insights


def propose_experiments(repo: Repository, campaign_id: int) -> Optional[list[dict]]:
    """Generate experiment proposals for one campaign. Returns list of
    {hypothesis, action, why} dicts, or None if insufficient data."""
    ours = get_learnings(repo, campaign_id)
    theirs = get_competitor_insights(repo, campaign_id)
    if not ours and not theirs:
        return None

    our_tried = _summarize_what_we_tried(repo, campaign_id)
    summary = {
        "our_learnings": ours or {},
        "our_tried": our_tried,
        "competitor_insights": theirs or {},
    }
    proposals = _ask_claude_for_experiments(repo, campaign_id, summary)
    return proposals


def refresh_and_notify(repo: Repository, campaign_id: Optional[int] = None) -> dict[int, list]:
    """Run on all campaigns with data; Telegram-send proposals."""
    if campaign_id is not None:
        ids = [campaign_id]
    else:
        with repo.conn() as c:
            ids = [r["id"] for r in c.execute(
                "SELECT id FROM campaigns WHERE status='active' OR status IS NULL"
            ).fetchall()]
    out: dict[int, list] = {}
    msgs: list[str] = []
    for cid in ids:
        props = propose_experiments(repo, cid)
        if not props:
            continue
        out[cid] = props
        title = _campaign_title(repo, cid)

        # Split: auto-testable (system queues them) vs dev-needed (asks Chris).
        auto = [p for p in props if p.get("auto_testable")]
        dev_needed = [p for p in props if not p.get("auto_testable")]

        if auto:
            # Queue the first auto experiment so the next explore slot picks it up.
            _queue_experiment(repo, cid, auto[0])

        lines = [f"<b>💡 Experiments for #{cid} {title}:</b>"]
        if auto:
            lines.append(f"\n<b>✅ Auto-queued ({len(auto)}) — system will test these:</b>")
            for i, p in enumerate(auto[:3], 1):
                queued_tag = " 🧪 <i>queued for next explore slot</i>" if i == 1 else ""
                lines.append(f"\n<b>{i}. {p.get('hypothesis', '?')}</b>{queued_tag}")
                lines.append(f"   <i>Action:</i> {p.get('action', '?')}")
                lines.append(f"   <i>Expected:</i> {p.get('expected_outcome', '?')}")
        if dev_needed:
            lines.append(f"\n<b>🛠 Needs your call ({len(dev_needed)}) — I can't auto-test these:</b>")
            for i, p in enumerate(dev_needed[:3], 1):
                lines.append(f"\n<b>{i}. {p.get('hypothesis', '?')}</b>")
                lines.append(f"   <i>Action:</i> {p.get('action', '?')}")
                lines.append(f"   <i>Expected:</i> {p.get('expected_outcome', '?')}")
                lines.append(f"   <i>To build:</i> {p.get('needs_dev_for', '?')}")
        msgs.append("\n".join(lines))
        _persist(repo, cid, props)

    if msgs:
        try:
            from publisher.telegram_gate import TelegramGate
            gate = TelegramGate()
            if gate.enabled:
                for m in msgs:
                    gate.notify(m)
        except Exception as e:
            logger.warning(f"[experimenter] telegram send failed: {e}")
    return out


# ----------------------------------------------------------------------
def _summarize_what_we_tried(repo: Repository, campaign_id: int) -> dict:
    """Summarize the dimensions across all this campaign's posted clips so
    Claude knows what we've sampled already."""
    with repo.conn() as c:
        rows = c.execute(
            "SELECT cl.duration_sec, cl.hook_text, cl.content_type, cl.caption_text "
            "FROM clips cl JOIN posts p ON p.clip_id = cl.id "
            "WHERE cl.campaign_id = ? AND p.status='posted'",
            (campaign_id,),
        ).fetchall()
    if not rows:
        return {"n_posted": 0}

    durations = [r["duration_sec"] for r in rows if r["duration_sec"]]
    styles = Counter(r["content_type"] for r in rows if r["content_type"])
    hooks = [r["hook_text"][:80] for r in rows if r["hook_text"]]
    return {
        "n_posted": len(rows),
        "style_counts": dict(styles),
        "min_duration": min(durations) if durations else None,
        "max_duration": max(durations) if durations else None,
        "hook_samples": hooks[:8],
    }


_EXPERIMENT_PROMPT = """You are the inventive strategist for a short-form clipping system.

Below is what we KNOW about a campaign — what's been working in our posts, what we've tried, and what competitor winners look like (where we have data).

Your job: propose 2 or 3 SPECIFIC, TESTABLE experiments to try next that could meaningfully improve performance. Be inventive: identify *gaps* between what we've tried and what competitors are doing, or propose entirely new angles competitors haven't tried either.

Constraints:
- Each experiment must be CONCRETE (not "post better content").
- Each must be testable in 1-3 clips.
- Each must have a clear hypothesis ("if X, then Y" form).
- Prefer experiments that close a gap (we haven't tried what competitors are doing) OR open a new dimension (no one is doing this yet).
- Avoid restating what we already know works — that's exploit, not explore.

For each experiment, classify whether the SYSTEM can run it itself OR
it needs a human to build new code/features first. The system currently controls these dimensions:
  - format_mode (smart / blur_pad / crop / letterbox / group_focus / auto)
  - hook_style (statement / question / wh-open / exclaim)
  - caption_voice (punchy / storytelling / informational / conversational)
  - hashtag count and selection
  - content_type pick bias (person-to-camera / reaction / demonstration / conversation / narration)
  - posting time-of-day slot
  - which platforms to publish to (subset of YT / IG / TT)
  - clip duration (within campaign's min/max)

If the experiment can be expressed entirely through those knobs, mark `auto_testable: true`
and fill in `system_params` with the concrete settings to apply.

If it requires new features (music overlay, vision changes, new visual effects, model swap, motion graphics, etc.) — mark `auto_testable: false` and explain what code would need to be built.

Return ONLY a JSON array, no commentary. Each element:
{
  "hypothesis": "<one short sentence stating the bet>",
  "action": "<concrete instruction the system can execute>",
  "why": "<one sentence: what gap/insight this exploits>",
  "expected_outcome": "<one sentence: what success looks like in numbers>",
  "auto_testable": true | false,
  "system_params": {<key>: <value>, ...}  // only when auto_testable=true
  "needs_dev_for": "<short description of what code Chris would need to build>"  // only when auto_testable=false
}

Data:
__DATA__
"""


def _ask_claude_for_experiments(
    repo: Repository,
    campaign_id: int,
    summary: dict,
) -> list[dict]:
    if not settings.anthropic_api_key:
        return []
    try:
        from engine import llm_compat as anthropic
    except ImportError:
        return []
    client = anthropic.Anthropic(api_key=settings.anthropic_api_key)
    prompt = _EXPERIMENT_PROMPT.replace("__DATA__", json.dumps(summary, indent=2)[:8000])
    try:
        resp = client.messages.create(
            model=settings.anthropic_model,
            max_tokens=900,
            messages=[{"role": "user", "content": prompt}],
        )
    except Exception as e:
        logger.warning(f"[experimenter] Claude call failed: {e}")
        return []
    text = "".join(b.text for b in resp.content if getattr(b, "type", "") == "text").strip()
    import re as _re
    cleaned = _re.sub(r"^```(?:json)?\s*|\s*```$", "", text, flags=_re.MULTILINE).strip()
    try:
        arr = json.loads(cleaned)
    except json.JSONDecodeError:
        logger.warning(f"[experimenter] unparseable: {text[:300]}")
        return []
    if not isinstance(arr, list):
        return []
    out = []
    for item in arr:
        if isinstance(item, dict) and item.get("hypothesis"):
            entry = {
                "hypothesis": str(item.get("hypothesis", ""))[:200],
                "action": str(item.get("action", ""))[:300],
                "why": str(item.get("why", ""))[:200],
                "expected_outcome": str(item.get("expected_outcome", ""))[:200],
                "auto_testable": bool(item.get("auto_testable", False)),
                "system_params": item.get("system_params") if isinstance(item.get("system_params"), dict) else {},
                "needs_dev_for": str(item.get("needs_dev_for", ""))[:300],
            }
            out.append(entry)
    return out


def _campaign_title(repo: Repository, campaign_id: int) -> str:
    with repo.conn() as c:
        row = c.execute("SELECT title FROM campaigns WHERE id=?", (campaign_id,)).fetchone()
    return (row["title"] if row else "(unknown)")[:40]


_COL_CHECKED = False
_QUEUE_COL_CHECKED = False


def _queue_experiment(repo: Repository, campaign_id: int, experiment: dict) -> None:
    """Persist the chosen auto-experiment so the orchestrator's explore-slot
    picks it up next time. The allocator reads `queued_experiment` and the
    scorer + producer apply its `system_params` (format_mode, hook_style,
    caption_voice, etc.)."""
    global _QUEUE_COL_CHECKED
    if not _QUEUE_COL_CHECKED:
        with repo.conn() as c:
            cols = {r["name"] for r in c.execute("PRAGMA table_info(campaigns)").fetchall()}
            if "queued_experiment" not in cols:
                c.execute("ALTER TABLE campaigns ADD COLUMN queued_experiment TEXT")
        _QUEUE_COL_CHECKED = True
    payload = {
        "experiment": experiment,
        "queued_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
    }
    with repo.conn() as c:
        c.execute(
            "UPDATE campaigns SET queued_experiment = ? WHERE id = ?",
            (json.dumps(payload), campaign_id),
        )


def get_queued_experiment(repo: Repository, campaign_id: int) -> Optional[dict]:
    """Return the queued experiment dict for this campaign, or None."""
    try:
        with repo.conn() as c:
            row = c.execute(
                "SELECT queued_experiment FROM campaigns WHERE id=?", (campaign_id,)
            ).fetchone()
        if not row or not row["queued_experiment"]:
            return None
        payload = json.loads(row["queued_experiment"])
        return payload.get("experiment")
    except Exception:
        return None


def clear_queued_experiment(repo: Repository, campaign_id: int) -> None:
    with repo.conn() as c:
        c.execute(
            "UPDATE campaigns SET queued_experiment = NULL WHERE id = ?",
            (campaign_id,),
        )


def _persist(repo: Repository, campaign_id: int, props: list[dict]) -> None:
    global _COL_CHECKED
    if not _COL_CHECKED:
        with repo.conn() as c:
            cols = {r["name"] for r in c.execute("PRAGMA table_info(campaigns)").fetchall()}
            if "experiments" not in cols:
                c.execute("ALTER TABLE campaigns ADD COLUMN experiments TEXT")
        _COL_CHECKED = True
    payload = {
        "proposals": props,
        "computed_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
    }
    with repo.conn() as c:
        c.execute(
            "UPDATE campaigns SET experiments = ? WHERE id = ?",
            (json.dumps(payload), campaign_id),
        )
